name: Build Module Terraform

on:
  push:
    branches:
      - "Az_Containers_Apps"

jobs:

  Terraform_fmt_check:
    name: Terraform fmt check
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out your repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@17d4c9b8043b238f6f35641cdd8433da1e6f3867
        with:
          terraform_version: 1.3.1      

    