name: Build Module Terraform

on:
  push:
    branches:
      - "Az_Containers_Apps"

jobs:

  Terraform_fmt_check:
    name: Terraform fmt check
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out your repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@17d4c9b8043b238f6f35641cdd8433da1e6f3867
        with:
          terraform_version: 1.3.1      

      - name: Run terraform fmt check
        id: var_output_fmt
        run: |
          terraform fmt -check -diff ./Modules/Az_Container_Apps

      - name: Recuperation du output Terraform fmt check
        if: ${{ failure() }}
        run: echo "${{ steps.var_output_fmt.outputs.stdout }}"

      - name: Creation d'un Timestamp Terraform fmt check
        if: ${{ failure() }}
        run: |
          echo "::set-output name=today::$(date "+%Y/%m/%d-%Hh-%Mm-%Ss")"
        id: var_timestamp_fmt

      - name: Creation "Terrafom fmt Issue"
        if: ${{ failure() }}
        uses: actions-ecosystem/action-create-issue@b02a3c1d9d929a5839315bd255e40389f0dab627
        with:
          github_token: ${{ secrets.github_token }}
          title: Error Terraform fmt ${{ steps.var_timestamp_fmt.outputs.today }}
          body: |
            ## Error Terraform fmt
            ${{ steps.var_output_fmt.outputs.stdout }}
          assignees: |
            Pierre-Chesne
          labels: |
            Error Terraform fmt check 

  Terraform_validate:
    name: Terraform validate 
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out your repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@17d4c9b8043b238f6f35641cdd8433da1e6f3867
        with:
          terraform_version: 1.3.1

      - name: Terraform validate
        id: var_output_validate
        run: |
          cd ./Modules/Az_Container_Apps       
          terraform init && terraform validate

      - name: Recuperation du output Terraform validate
        if: ${{ failure() }}
        run: echo "${{ steps.var_output_validate.outputs.stderr }}"

      - name: Creation d'un Timestamp Terraform validate
        if: ${{ failure() }}
        run: |
          echo "::set-output name=today::$(date "+%Y/%m/%d-%Hh-%Mm-%Ss")"
        id: var_timestamp_validate

      - name: Creation "Terrafom validate Issue"
        if: ${{ failure() }}
        uses: actions-ecosystem/action-create-issue@b02a3c1d9d929a5839315bd255e40389f0dab627
        with:
          github_token: ${{ secrets.github_token }}
          title: Error Terraform fmt ${{ steps.var_timestamp_validate.outputs.today }}
          body: |
            ## Error Terraform validate
            "${{ steps.var_output_validate.outputs.stderr }}"
          assignees: |
            Pierre-Chesne
          labels: |
            Error Terraform validate

